### ISSUE TITLE
calcurse-caldav no such file or directory: /.local/share/calcurse/caldav/lock

### ISSUE THREAD

**Issue by tcullum-rh** [lfos/calcurse#291] opened 2020-05-19 19:58 UTC
Hello,

VERSION INFO:

calcurse 4.6.0
Python: 3.7.6
OS: Fedora 31

I am trying to setup calcurse-caldev to sync with my Google calendar. I followed the steps in the docs and got the client secret/client id. I then had to manually create a new config file, as one did not yet exist in calcurse-caldev. One DID exist in calcurse but the format looked different and when I launched caldev, it tried to find it in another path which was separate from main calcurse. So I assumed that I should *create* this file. I did so, and put my config in it in both the [General] and [OAuth2] sections as described by the docs. I also did install python oauth2client (v 4.1.3) I am going to paste my terminal to show what is going on:

```
~ $ cd /home/moveax41h/.config/calcurse/
~/.config/calcurse $ ls
conf  hooks  keys
~/.config/calcurse $ vim conf
~/.config/calcurse $ calcurse-caldav
error: Configuration file not found:
error: /home/moveax41h/.config/calcurse/caldav/config
~/.config/calcurse $ mkdir caldav
~/.config/calcurse $ cd caldav
~/.config/calcurse/caldav $ mv ~/.local/share/calcurse/conf /home/moveax41h/.config/calcurse/caldav/config
~/.config/calcurse/caldav $ calcurse-caldav
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Traceback (most recent call last):
  File "/usr/local/bin/calcurse-caldav", line 706, in <module>
    open(lockfn, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/home/moveax41h/.local/share/calcurse/caldav/lock'
~/.config/calcurse/caldav $ ls
config
~/.config/calcurse/caldav $ vim config
~/.config/calcurse/caldav $ calcurse-caldav
Traceback (most recent call last):
  File "/usr/local/bin/calcurse-caldav", line 706, in <module>
    open(lockfn, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/home/moveax41h/.local/share/calcurse/caldav/lock'
```

You can see the locations of my file, which match the one that caldev is looking for. However, it is looking for some lock file that is not there.
I added the specified DryRun line and I still get the lock error though.

Thanks for creating this awesome tool!

**Comment by lfos** [comment] 2020-05-19 22:58
Duplicate of #283. A fix is in master already; as a workaround, run `mkdir -p .local/share/calcurse/caldav/` before running calcurse-caldav.

**Closed by lfos** 2020-05-19 22:58 UTC
