### ISSUE TITLE
Calcurse shows "MM-CM-$rz" instead of "März" (German for month march)

### ISSUE THREAD

**Issue by uboubo** [lfos/calcurse#355] opened 2021-03-14 20:53 UTC
I can see this issue in the calendar-panel as well as in the appointment-panel. All other months are displayed correctly.
Running it with `LC_ALL=de_DE calcurse` or `LC_ALL=de_DE.ISO8859-1 calcurse` doesn't help.

I compiled and installed calcurse 4.7.0 on Ubuntu 18.04.5.

**Comment by lhca** [comment] 2021-03-15 06:53
`LC_ALL=de_DE.utf8 calcurse` or similar should do it.

**Comment by uboubo** [comment] 2021-03-15 14:54
Thanks a lot for your response, lhca!
I tried `LC_ALL=de_DE.utf8 calcurse` without success.
And I also recompiled calcurse after configering with `./configure --with-libintl-prefix=/usr/include/libintl.h` . No success as well.

**Comment by lhca** [comment] 2021-03-15 17:04
You must find the right locale to use. Locale names are system-specific. Use `locale -a` to get a list of all supported locales on your system. You need a locale with the Unicode character set. Usually they have UTF-8 (the character encoding) or something like that in the name.

**Comment by uboubo** [comment] 2021-03-15 18:52
With `locale -a` I see, that `de_DE.utf8` is available, and with `LC_ALL=de_DE.utf8 calcurse` I get calcurse in German.
But instead of "März" I still get "MM-CM-$rz".

**Comment by lhca** [comment] 2021-03-19 22:09
Unfortunately, I cannot reproduce the behaviour. On my system `LC_ALL=de_DE.utf8 calcurse` causes `März` to be displayed.

However, I have had a look at the source file, and it does employ a dubious technique to access the names of the months (I wrote the code). It's not difficult to fix, but I cannot test whether it solves the problem. Would you be willing to try it out?

I also noticed another minor bug: in german the abbriviated day names (Mo, Di, Mi, ...) have two characters each, but the code assumes three (as in Mon, Tue, ..., or lun, mar, ...) which means that the german names are not properly aligned.

**Comment by uboubo** [comment] 2021-03-21 12:38
Sorry for delay!
Even if it will not solve my "problem", it would be my pleasure if I can help in any way.

**Comment by lhca** [comment] 2021-03-21 19:12
Originally you wrote:

> I can see this issue in the calendar-panel as well as in the appointment-panel. All other months are displayed correctly.

And later

> With `locale -a` I see, that `de_DE.utf8` is available, and with `LC_ALL=de_DE.utf8 calcurse` I get calcurse in German.
> But instead of "März" I still get "MM-CM-$rz".

Is that so in the calendar panel as well as in the appointments panel? The reason I ask is that  the month name is produced differently in the two panels. The dubious technique mentioned above only pertains to the calendar panel. If the appointments panel still has the problem when you run `LC_ALL=de_DE.utf8 calcurse`, I'm afraid that the reason lies outside `calcurse`.

**Comment by uboubo** [comment] 2021-03-22 08:17
Yes, instead of "März" I still get "MM-CM-$rz" in both panels. If you get other ideas in the future, what I could check, I really will like to try. But don't worry! It's no real problem at all! Thanks a lot!

**Comment by lhca** [comment] 2021-03-22 10:52
Whether it's a real problem is for you to decide, but it is with your system, not with `calcurse`.

What is the value of the configuration variable "format.dayheading" (in the `conf` file)?

**Comment by uboubo** [comment] 2021-03-22 22:40
In the meantime, I also believe that the cause is to be found in my system. Well, hopefully not in front of my monitor.

The line in conf is `format.dayheading=%B %e, %Y`

**Comment by lhca** [comment] 2021-03-23 15:55
That's the default day heading format string.

It's used as the template argument in a call of the clib-function `strftime()` to produce the output string. That's the best `calcurse` can do.

**Comment by lfos** [comment] 2021-04-03 16:50
Thanks for investigating this, @lhca and @uboubo. Since it looks like this is a local configuration issue, I am closing the issue for now. Please reopen if it turns out that this is a bug in calcurse.

**Closed by lfos** 2021-04-03 16:50 UTC
