### ISSUE TITLE
Selfsigned ssl certificate

### ISSUE THREAD

**Issue by Pitido** [lfos/calcurse#420] opened 2022-04-07 13:14 UTC
Version information: 4.7.1 selfcompiled on a Debian Bullseye host.

Bug description: calcurse-caldav  --init=keep-remote refused my selfsigned certificate on a selfhosted Nextcloud Server (Raspberry Pi)

`calcurse-caldav  --init=keep-remote
Connecting to 192.168.x.x/nextcloud...
Removing all local calcurse objects...
Traceback (most recent call last):
  File "/usr/local/bin/calcurse-caldav", line 770, in <module>
    etagdict = get_etags(conn)
  File "/usr/local/bin/calcurse-caldav", line 343, in get_etags
    headers, body = remote_query(conn, "REPORT", absolute_uri, headers, body)
  File "/usr/local/bin/calcurse-caldav", line 304, in remote_query
    resp, body = conn.request(path, cmd, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1363, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1155, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)
`

Expected Behavior: Calcurse should create the initial setup.

My config in ~/.calcurse

`[General]

Binary = calcurse

Hostname = 192.168.x.x/nextcloud/

Path = /remote.php/dav/calendars/user/path/

AuthMethod = basic

InsecureSSL = Yes

HTTPS = Yes

....`

I guess "InsecureSSL = Yes" should avoid the check.

Thank you for any tipp!

Kind regards

Pitido

**Comment by lfos** [comment] 2022-04-16 21:52
Thanks for the bug report; it looks like there was a regression that broke `InsecureSSL`. A fixed has been merged into `pu`. Marking as resolved, please reopen if the issue persists.

**Closed by lfos** 2022-04-16 21:52 UTC
