### ISSUE TITLE
ValueError not enough Values - calcurse-caldav after the initial sync

### ISSUE THREAD

**Issue by fosBHY** [lfos/calcurse#186] opened 2019-02-23 10:23 UTC
The initial sync worked for me:
calcurse-caldav --init=keep-remote

however, any following sync without the --init spits out an error. I dont want to use --init=two-way as calcurse-caldav did end up duplicating lots all my events on the remote server (baikal), but that might be another issue.

```
$
$ calcurse-caldav --init=keep-remote
/usr/bin/calcurse-caldav:501: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open(configfn))
Connecting to XXX...
Removing all local calcurse objects...

[USER EDITED: IMPORTING OF EVENTS]

Saving synchronization database to /home/X/.calcurse/caldav/sync.db...
380 items imported, 0 items removed locally.
0 items exported, 0 items removed from the server.
$
$
$
$ calcurse-caldav 
/usr/bin/calcurse-caldav:501: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open(configfn))
Connecting to XXX...
Loading synchronization database from /home/X/.calcurse/caldav/sync.db...
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 618, in <module>
    syncdb = get_syncdb(syncdbfn)
  File "/usr/bin/calcurse-caldav", line 263, in get_syncdb
    href, etag, objhash = line.rstrip().split(' ')
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by lfos** [comment] 2019-02-23 12:46
Duplicate of #20. There is a WIP PR (#60) for implementing this but it's stalled.

**Closed by lfos** 2019-02-23 12:46 UTC
