### ISSUE TITLE
Bug : calcurse-cadav "args.c: 872: invalid argument combination"

### ISSUE THREAD

**Issue by LexTek** [lfos/calcurse#177] opened 2019-02-01 11:18 UTC
Hello, i'm on the commit 0169ba0934be04199a4e29fd8613d9c6f8f676f8

I want to synchronize calcurse with a nextcloud server.

I tried the version 4.3.0. The import of some caldav events worked but I got this bug : https://github.com/lfos/calcurse/issues/20 .
With some edits of caldav/sync.db I have got calcurse to show my remote events. I assume my config file is correct (I use basic authentication FYI).

On the commit aforementioned I get theses errors with the command "calcurse-caldav --init=keep-remote" : 
```
Connecting to cloud.****.fr...
Removing all local calcurse objects...
Importing new object ****.
args.c: 872: invalid argument combination
Failed to import object: **** (/remote.php/dav/calendars/****/personal/****.ics)
... (this error repeats for all objects)
Saving synchronization database to /home/****/.calcurse/caldav/sync.db...
0 items imported, 0 items removed locally.
0 items exported, 0 items removed from the server.
```

**Comment by LexTek** [comment] 2019-02-02 16:45
Yes ! It works now. There is still an object that can't be imported. I don't really know which event it is.
```
calcurse-caldav --init=keep-remote
Connecting to cloud.lacl.fr...
Removing all local calcurse objects...
Importing new object ****.
... (it repeats)
Some items could not be imported.
See /tmp/calcurse_log.Rt7pOl for details.
Failed to import object: **** (/remote.php/dav/calendars/fernandez/personal/****.ics)
Importing new object ****
... (it repeats)
Saving synchronization database to /home/alexiram/.calcurse/caldav/sync.db...
17 items imported, 0 items removed locally.
0 items exported, 0 items removed from the server.
```

**Comment by grimmn** [comment] 2019-02-10 06:56
I had a similar issue when trying to sync calcurse to my Radicale server. I narrowed down the issue to the `optind < argc` check on line 866 of `src/args.c`. Running `calcurse-caldav --init=two-way` tries to `calcurse -x ical --export-uid --filter-hash=*****` which fails the check with optind equal to 4 and argc equal to 5.

**Comment by lhca** [comment] 2019-02-10 19:28
This one is caused by the `-x ical` part of the command line. The option `-x` takes an optional argument that, if present, must be given as either `-xical` or (long option) `--export=ical`.

**Comment by lfos** [comment] 2019-02-10 20:43
Should be fixed now.

**Comment by lfos** [comment] 2019-02-13 05:50
Will close for now, please reopen if it still does not work.

**Closed by lfos** 2019-02-13 05:50 UTC
