### ISSUE TITLE
Calcurse-Caldav - Posteo?

### ISSUE THREAD

**Issue by HolzCode** [lfos/calcurse#350] opened 2021-02-02 02:55 UTC
Posteo seems to be a very well regarded option for a private and FOSS friendly mail and calendar provider.

After configuring the `~/.calcurse/caldav/config` correctly, to reflect the exact settings in thunderbird, I tried to initialize the database.
`calcurse-caldav --init=keep-remote`

But, even with the seemingly correct settings, I get a 401 unauthorized response from their servers, even though with the exact same settings thunderbird works fine.

```
Hostname = posteo.de:8443   // Have tried with and without port number.
Path = calendars/my.username/default   // Have tried with proceeding / trailing slash

InsecureSSL = No
HTTPS = Yes
SyncFilter = cal
DryRun = Yes
Verbose = Yes

AuthMethod = basid
Username = my.username   // Have tried with @posteo.net
Password = <my password>
```

Does anyone have experience with Posteo and Calcurse-Caldav?

**Comment by ChelonianEgghead** [comment] 2021-02-05 17:50
I'm having almost the exact same issue with Mailfence, though in my case I had to use `InsecureSSL = Yes` because of another unrelated issue. Relevant connection information for Mailfence is [here](https://kb.mailfence.com/kb/how-can-i-synchronize-mailfence-contacts-and-calendar-events-with-thunderbird-using-caldav-and-carddav/).

**Comment by marcusboden** [comment] 2021-03-03 10:00
1. `AuthMethod = basic` (typo, I guess)
2. You need `[Auth]` above Username/Password

```
[...]
AuthMethod = basic
[Auth]
Username = my.username@posteo.net
Password = <my password>
```

**Comment by lfos** [comment] 2021-04-03 22:16
I'm closing this since based on the last comment, I assume the issue is resolved after fixing typos. I also merged a commit to improve error handling and catch typos in the config file. Please feel free to reopen if the issue persists.

**Closed by lfos** 2021-04-03 22:16 UTC
