### ISSUE TITLE
if authmethod is 'oauth2' this error will trigger

### ISSUE THREAD

**Issue by holalluis** [lfos/calcurse#151] opened 2018-09-27 12:39 UTC
https://github.com/lfos/calcurse/blob/ea0a33645a782d8d7531d78c39fe58f116c8d30d/contrib/caldav/calcurse-caldav.py#L696

**Comment by lfos** [comment] 2018-09-27 12:42
Dupe of #149. I have a patch which I will push later today.

**Closed by lfos** 2018-09-27 12:42 UTC
