### ISSUE TITLE
PasswordCommand not working

### ISSUE THREAD

**Issue by letscho123** [lfos/calcurse#457] opened 2023-04-23 21:14 UTC
**Version information.**  4.8.0

**Bug description.**
When I run `calcurse-caldav --init=keep-remote` I get the error:
`error: Unexpected config key in section Auth: PasswordCommand`

Here is the relevant section of my config file:
```
# Credentials for HTTP Basic Authentication (if required).
# Set `Password` to your password in plaintext (unsafe),
# or `PasswordCommand` to a shell command that retrieves it (recommended).
[Auth]
Username = user
#Password = password
PasswordCommand = pass baikal
```

When I uncomment the [Auth] section I get the output:
```
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Connecting to localhost:37358...
Removing all local calcurse objects...
error: The server at localhost:37358 replied with HTTP status code 401
error: (Unauthorized) while trying to access http://localhost:37358/user/.
```

Am I doing something wrong?

**Comment by lfos** [comment] 2023-04-23 23:04
Support for the `PasswordCommand`  option has been merged ~1.5 weeks ago and is not part of any release yet.

**Comment by Aresime** [comment] 2023-08-04 13:18
I tried this today and had no problems.  Do you still have issues?

**Comment by Gavilaan** [comment] 2023-08-29 11:48
Having the same problem. Running 4.8.1 against a davical server. It works fine if i put my password into the configfile, produces a 401 when i use the the PasswordCommand. The apacheserver in front of davical logs a "password mismatch"

```
[Auth]
Username = trupp
PasswordCommand = pass flik

```
`pass flik`

at the console shows the correct password.

Any idea?
Thanks Gav

**Comment by eggersn** [comment] 2023-09-26 09:15
@Gavilaan this seems to be caused by the issue described in #473

**Comment by Maaxxs** [comment] 2023-11-09 16:24
fixed in d4eb9f85d07351e184ba16ff91c327425653d3e9

**Closed** 2023-11-10 13:02 UTC

**Comment by BoostCookie** [comment] 2025-03-18 22:17
It's good that this was fixed, but I just encountered this error, because the latest version in the Arch repositories is the latest release which is v4.8.0. That release is at this point almost 3 years old.

Is there a reason for the lack of releases?

**Comment by Maaxxs** [comment] 2025-03-19 07:38
yeah, you're right. Arch Linux uses 4.8.1 via the calcurse website (Arch Linux [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/calcurse/-/blob/main/PKGBUILD?ref_type=heads)). [Release Notes for 4.8.1 from 2023-05-22](https://calcurse.org/files/changes.html) 

The commit fixing this issue was included on Nov 6, 2023 so it's not part of that release. (I downloaded the release tar.gz and verified it).
I'm still using the version I built myself so I didn't notice this. Thanks for mentioning, @BoostCookie 

I also didn't find the tag v4.8.1 in the checkout via https://git.calcurse.org/calcurse.git 
@lfos can you update this when you've got some time?
