### ISSUE TITLE
ValueError: need more than 1 value to unpack [@ calcurse-caldav:263 get_syncdb]

### ISSUE THREAD

**Issue by mcepl** [lfos/calcurse#91] opened 2018-03-25 21:07 UTC
Using calcurse-4.3.0-2.el7.x86_64 from the Fedora/Rawhide package rebuild on RHEL-7 with python 3.4.8. My first try on using calcurse.
```
matej@mitmanek: .calcurse$ calcurse-caldav --init=two-way
Connecting to hubmaier.ceplovi.cz...
Importing new object e92b87257b3f3b0a45df04545ba19a8e.
[...]
Importing new object 0af137a1a3c0280623a83744b3b0e71c.
Saving synchronization database to /home/matej/.calcurse/caldav/sync.db...
378 items imported, 0 items removed locally.
0 items exported, 0 items removed from the server.
matej@mitmanek: .calcurse$ calcurse  # changing description with one appointment
matej@mitmanek: .calcurse$ calcurse-caldav
Connecting to hubmaier.ceplovi.cz...
Loading synchronization database from /home/matej/.calcurse/caldav/sync.db...
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 618, in <module>
    syncdb = get_syncdb(syncdbfn)
  File "/usr/bin/calcurse-caldav", line 263, in get_syncdb
    href, etag, objhash = line.rstrip().split(' ')
ValueError: need more than 1 value to unpack
matej@mitmanek: .calcurse$ 
```

**Comment by lfos** [comment] 2018-05-01 17:29
Sounds like a duplicate for #20 to me. Do you use iCloud?

**Comment by lfos** [comment] 2018-08-25 06:59
Duplicate of #20.

**Closed by lfos** 2018-08-25 06:59 UTC
