### ISSUE TITLE
hard hang when using hooks for sync'ing with caldav

### ISSUE THREAD

**Issue by craftyguy** [lfos/calcurse#78] opened 2017-12-14 19:03 UTC
I am using a script for both `post-save` and `pre-load` hooks, based on your example script ([you can view it here](http://dpaste.com//1FDGP8H)), and experience a hard hang in calcurse after calcurse has been open for some number of minutes and I hit the shift+r to reload. It doesn't seem to matter if I hit 's' to save first (or not), and there have been no new appointments added between when I first open calcurse and hit shift+r.

Steps to reproduce:

1) save [this script](http://dpaste.com//1FDGP8H) as both `~/.calcurse/hooks/post-save` and `~/.calcurse/hooks/pre-load` (change password env. var as appropriate)

2) Launch calcurse. The pre-load hook should trigger and shows in the log file at `~/.calcurse/caldav/log`, so far so good!

3) leave calcurse alone for a few minutes (exact time hasn't been determined yet.., try ~10min)

4) hit shift+r in calcurse. it will hard-hang.

If I remove the hooks then I do not get this hang even after running calcurse for several days.

**Comment by lfos** [comment] 2017-12-15 06:01
Just a guess: Do you use `general.periodicsave`? What is the value of the `general.systemdialogs` setting?

**Comment by craftyguy** [comment] 2017-12-15 16:58
> Do you use general.periodicsave?

Yes!


> What is the value of the general.systemdialogs setting?

`general.systemdialogs = no `

**Comment by craftyguy** [comment] 2017-12-17 17:56
Disabling autosave doesn't seem to help, for what it's worth.

**Comment by vaygr** [comment] 2017-12-27 14:52
I can confirm exactly the same behavior. I do not use caldav to sync though, just a remote Mercurial repo.

The issue seems to disappear once I set `general.periodicsave` to `0`.

**Comment by vaygr** [comment] 2017-12-28 21:48
Just a quick note: I couldn't remember such a weird behavior with calcurse **4.2.2**.

**Comment by lfos** [comment] 2018-05-19 08:37
Sorry for coming back so late. Do you still experience those issues? I just pushed a commit that might help fix the issue. If the issue persists, could you try to bisect?

**Comment by craftyguy** [comment] 2018-05-21 23:57
Someone else will have to comment on this since I no longer use calcurse.

**Comment by vaygr** [comment] 2018-05-23 12:53
Yeah, I believe for me it highly depends on #98

**Comment by vaygr** [comment] 2018-05-30 02:29
It seems the issue is still there. I was able to reproduce it after my laptop got out of the hibernation mode in the morning.

**Comment by vaygr** [comment] 2018-05-30 02:32
When I attach to the process with strace I see this:

```futex(0x632ae0, FUTEX_WAIT_PRIVATE, 2, NULL```

**Comment by vaygr** [comment] 2018-06-09 00:50
I also see it's very easy to reproduce:

1. set `general.periodicsave` to 5
2. put your computer in sleep/hibernate
3. wait 5-10m
4. recover your computer from sleep/hibernate
5. wait for <5m

it'll freeze just in time when it tries to autosave I believe.

**Comment by lhca** [comment] 2018-06-10 06:32
How do you detect the "freeze"? Not responsive to commands?

Is the clock running in the notify bar?

**Comment by vaygr** [comment] 2018-06-10 12:12
Yeah, exactly, no responsiveness to commands and the clock stops.

**Comment by lhca** [comment] 2018-06-10 15:59
@vaygr I expected as much. I suspect we have been barking up the wrong tree so far. But before delving into that an element of uncertainty should be removed, although I don't believe it is the problem: it is possible to have several periodic save threads running simultaneously.

@lfos I have uploaded a patch and opened a pull request lfos/calcurse#114.

**Comment by lhca** [comment] 2018-06-11 08:01
@vaygr You have already shown (with strace) that a mutex is involved. But there are several. Some are related to the screen and the notify bar. Would it be possible for you with a debugger to attach to calcurse? And produce backtraces of the threads?

**Comment by lhca** [comment] 2018-06-12 07:13
@vaygr Another possibility:

- assuming that the periodic save thread gets into a deadlock (on a mutex) and that
- you can reproduce that deadlock,

with `strace -p <pid>` attach to the periodic save thread before the deadlock happens and wait for the deadlock. Output from strace goes to stderr or to a file with `-o <file`.

**Comment by lhca** [comment] 2018-08-19 05:44
Three? Usually it is four:

1. the main program
2. the notification bar (updates the clock below the three panels)
3. calendar thread (changes date at midnight)
4. periodic save

They are started in that order, so the periodic save thread should be the one with the highest lwp.

**Comment by lfos** [comment] 2019-03-03 19:19
Did anybody test the current release? There haven been several improvements to code dealing with concurrency. Is this hard hang still reproducible?

**Comment by vaygr** [comment] 2019-03-03 19:22
Thanks for the update @lfos, I'll test this release and report back.

**Comment by vaygr** [comment] 2019-03-04 04:09
@lfos I think it's gone. Can't reproduce it.

So it should be safe to close this issue.

**Comment by lfos** [comment] 2019-03-04 04:44
Great!

**Closed by lfos** 2019-03-04 04:44 UTC
