### ISSUE TITLE
CalDAV syncing working except for tasks

### ISSUE THREAD

**Issue by ramblingenzyme** [lfos/calcurse#55] opened 2017-10-24 22:04 UTC
I've setup Google Calendar syncing with calcurse-caldav, and it's working great except that if I have TODO tasks, it tries and fails to sync them with a 403 on apidata.googleusercontent.com/caldav/user@gmail.com/events/something.ics

**Comment by watersalesman** [comment] 2017-10-24 22:40
Hmmm interesting. What kind of task is this and how did you go about creating it? I only ask because I have synced successfully despite having reminders and tasks (it ignores them since they are not calendar events). If you let me know how you made it, I can go about reproducing and troubleshooting the error.

**Comment by ramblingenzyme** [comment] 2017-10-24 23:47
Sorry, I don't think I made it clear enough that I'm talking about todo items in calcurse made locally. If I have any todo items in calcurse, the sync script tries to upload them to Google Calendar and fails on an endpoint it gets a 403 on.

**Comment by watersalesman** [comment] 2017-10-25 00:25
Ok I understand now. I reproduced it on my end.

The problem is that, while TODO items are exported in an appropriate iCalendar/CalDAV format, Google just isn't having it on their end since Google Calendar does not support TODO items at all.

I will look into how the script could avoid exporting TODO items when syncing using OAuth2.

**Comment by ramblingenzyme** [comment] 2017-10-25 00:31
https://github.com/lfos/calcurse/blob/efd76a0d995292e48f5466fccada4901618f7d97/contrib/caldav/calcurse-caldav.py#L77 is where the issue comes from. For the moment, I've just removed it from my local version.

I think the correct way would be to add a config option under [General] to disable syncing todos, and allow users to disable it as needed.

**Comment by lfos** [comment] 2017-11-10 05:50
PR #56 has been merged; you can use the `SyncFilter` option to only synchronize events/appointments now.

**Closed by lfos** 2017-11-10 05:50 UTC

**Comment by paindespik** [comment] 2022-05-02 00:19
It would be great if it could sync the todo with google tasks
