### ISSUE TITLE
Calcurse removed from Debian Testing repos

### ISSUE THREAD

**Issue by jordan31bit** [lfos/calcurse#411] opened 2022-02-09 02:46 UTC
**Bug description.** 
Calcurse has been removed from Debian Testing repos. Not sure if its in the current stable repo.

**Reproduce.**
apt-get search calcurse

**Expected Behavior.**
To be in the Debian repos

**Comment by hiqua** [comment] 2022-03-08 06:27
Explanations: https://qa.debian.org/excuses.php?package=calcurse

**Comment by lhca** [comment] 2022-03-08 16:44
This appears to be a consequence of #397 which is still open.

The issue is a build problem on big-endian architectures. Because endian-ness is not detected by the calcurse autoconf setup, the SHA1-algorithm used by calcurse is always compiled as for a small-endian system. The resulting hashes are OK, but not those of SHA1. This has always been so, but has not caused any problems because the hashes are used internally(?) only, and there is no test (in the test-suite) for the correct SHA1 hashes.

Back in 2020, a test script was changed in a way that relies on the correct SHA1-hashes (ical-003.sh in commit d2791b04, Update import of basic recurrence rules). See the discussion in #397. Since calcurse v7.4.0, this test will fail on big-endian systems.

The issue should be solved as suggested in https://github.com/lfos/calcurse/pull/399#issuecomment-944938572 (which is also still open).

**Comment by lfos** [comment] 2022-03-11 16:39
Thank for reporting! I just pushed a fix to the pu branch (but unfortunately couldn't test on a big-endian system to confirm). I'll close this as a duplicate of #397; we can continue the discussion there.

**Closed by lfos** 2022-03-11 16:39 UTC
