### ISSUE TITLE
calcurse-caldav: Cannot sync

### ISSUE THREAD

**Issue by rslindee** [lfos/calcurse#182] opened 2019-02-13 05:41 UTC
After running a successful calcurse-caldav --init with my Google calendar, I created a new appointment.

After the appointment was created, I went ahead and attempted to run calcurse-caldav to sync and received the following output (via "calcurse-caldav --debug -v"):

Loading configuration from /home/rich/.calcurse/caldav/config...
/usr/bin/calcurse-caldav:501: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open(configfn))
Connecting to apidata.googleusercontent.com...
Loading synchronization database from /home/rich/.calcurse/caldav/sync.db...
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 618, in <module>
    syncdb = get_syncdb(syncdbfn)
  File "/usr/bin/calcurse-caldav", line 263, in get_syncdb
    href, etag, objhash = line.rstrip().split(' ')
ValueError: not enough values to unpack (expected 3, got 1)

Any suggestions for what might be the culprit? This is running calcurse 4.3.0 in Arch Linux.

**Comment by lfos** [comment] 2019-02-13 05:49
Duplicate of #20. There is a WIP PR (#60) for implementing this but it's stalled.

**Closed by lfos** 2019-02-13 05:49 UTC
